---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/
---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
